layout_spectrum: 0.2241839
color:
  saturation: 0.06244786
  lightness: 0.4915103
  brandStrength: 0.4299321
  brandColors:
    - '#FFFEFF'
    - '#181417'
    - '#5B4C41'
    - '#BE6543'
    - '#F2A47F'
  rhythmicContrast: 0.609997
typography_spectrum: 0.08057263
name: Consciousness is a dimension
